name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'auto-clipper-web/**'
      - '.github/workflows/deploy-firebase.yml'
  workflow_dispatch:

jobs:
  deploy_firebase:
    name: 🚀 Deploy Web App to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          entryPoint: ./auto-clipper-web
        continue-on-error: true
